apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type:  {{ .Values.specType }}
  ports:
    - targetPort:  {{ .Values.ports.targetPort }}
      port:  {{ .Values.ports.port }}
      nodePort:  {{ .Values.ports.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image:  "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy:  {{ .Values.imagePullPolicy }}
          ports:
            - containerPort:  {{ .Values.ports.containerPort }}
