apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    type: env-secret
data:
  NAME: {{ .Values.secret.data.name | b64enc }}
  PASSWORD: {{ .Values.secret.data.password | b64enc }}
  SECRET: {{ .Values.secret.data.secret | b64enc }}
