appName: my-bookstore-app
containerName: my-app
replicas: 2

serviceName: my-bookstore-service
imagePullPolicy: Always
specType: LoadBalancer
ports:
  protocol: TCP
  containerPort: 3000
  targetPort: 3000
  port: 3000
  nodePort: 30002

image:
  name: shn27/book-store
  tag: "2.0"

secret:
  name: env-secrets
  namespace: default
  data:
    NAME: "admin"
    PASSWORD: "1234"
    SECRET: "hfdjksh732hihyf9"
